# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 15) do

  create_table "action_logs", :force => true do |t|
    t.column "user_id",     :integer
    t.column "action_code", :string
    t.column "created_on",  :time
    t.column "dis_code",    :integer
  end

  create_table "ent_levels", :force => true do |t|
    t.column "level", :integer
  end

  create_table "ent_modules", :force => true do |t|
    t.column "module_name", :integer
    t.column "module_src",  :text
  end

  create_table "ent_operations", :force => true do |t|
    t.column "operation_code", :string
  end

  create_table "ent_questions", :force => true do |t|
    t.column "question_name", :string
    t.column "max_point",     :integer
  end

  create_table "ent_seqs", :force => true do |t|
    t.column "seq_src",   :text
    t.column "seq_title", :string
  end

  create_table "ent_tests", :force => true do |t|
    t.column "test_name",     :string
    t.column "max_sum_point", :integer
  end

  create_table "level_logs", :force => true do |t|
    t.column "user_id",      :integer
    t.column "ent_seq_id",   :integer
    t.column "ent_level_id", :integer
    t.column "created_on",   :time
  end

  create_table "module_logs", :force => true do |t|
    t.column "user_id",       :integer
    t.column "ent_seq_id",    :integer
    t.column "ent_module_id", :integer
    t.column "created_on",    :time
  end

  create_table "operation_logs", :force => true do |t|
    t.column "user_id",          :integer
    t.column "ent_seq_id",       :integer
    t.column "ent_operation_id", :integer
    t.column "event_arg",        :string
    t.column "created_on",       :time
    t.column "dis_code",         :integer
  end

  create_table "question_logs", :force => true do |t|
    t.column "user_id",         :integer
    t.column "ent_seq_id",      :integer
    t.column "ent_module_id",   :integer
    t.column "ent_test_id",     :integer
    t.column "ent_question_id", :integer
    t.column "point",           :integer
    t.column "created_on",      :time
  end

  create_table "rule_search_time_logs", :force => true do |t|
    t.column "user_id",    :integer
    t.column "time_name",  :string
    t.column "time_value", :time
  end

  create_table "seq_logs", :force => true do |t|
    t.column "user_id",    :integer
    t.column "ent_seq_id", :integer
    t.column "created_on", :time
  end

  create_table "test_logs", :force => true do |t|
    t.column "user_id",       :integer
    t.column "ent_seq_id",    :integer
    t.column "ent_module_id", :integer
    t.column "ent_test_id",   :integer
    t.column "sum_point",     :integer
    t.column "created_on",    :time
  end

  create_table "users", :force => true do |t|
    t.column "login",           :string,   :limit => 80, :default => "", :null => false
    t.column "salted_password", :string,   :limit => 40, :default => "", :null => false
    t.column "email",           :string,   :limit => 60, :default => "", :null => false
    t.column "firstname",       :string,   :limit => 40
    t.column "lastname",        :string,   :limit => 40
    t.column "salt",            :string,   :limit => 40, :default => "", :null => false
    t.column "verified",        :integer,                :default => 0
    t.column "role",            :string,   :limit => 40
    t.column "security_token",  :string,   :limit => 40
    t.column "token_expiry",    :datetime
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
    t.column "logged_in_at",    :datetime
    t.column "deleted",         :integer,                :default => 0
    t.column "delete_after",    :datetime
  end

end
